name: Update Flusight forecasts
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 3' # every Wednesday (3) at 6 PM ET (11 PM UTC)

jobs:
  run_script:
    if: github.repository_owner == 'reichlab'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout flu-hosp-forecasts repo
      uses: actions/checkout@v3
      with:
        path: flu-hosp-forecasts
    
    - name: Setup GitHub Action for R language
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies ## at least curl needed for R package curl
      run: sudo apt-get install libudunits2-dev libcurl4-openssl-dev libgdal-dev

    - name: Install R script dependencies
      working-directory: ./flu-hosp-forecasts
      run: Rscript .github/workflows/install_dependencies.R
      env:
        GITHUB_PAT: ${{secrets.GH_TOKEN}}

    - name: Clone Github Repo Action
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
          owner: 'cdcepi'
          repository: 'Flusight-forecast-data'
      
    - name: Access cloned repository content
      run: |
        echo "ROOT"
        ls -la
        echo "CLONED REPO"
        cd Flusight-forecast-data
        ls -la
        
    - name: convert and upload flusight forecasts
      working-directory: ./flu-hosp-forecasts
      run: Rscript code/convert-upload-forecast-files.R
      env:
        Z_USERNAME: ${{ secrets.Z_USERNAME }}
        Z_PASSWORD: ${{ secrets.Z_PASSWORD }}
        
    - name: Push generated files to GitHub
      run: bash .github/workflows/push-flu-hosp-gh.sh
      working-directory: ./flu-hosp-forecasts
      env:
        GITHUB_PAT: ${{secrets.GH_TOKEN}}
